### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by risangbaskoro** [C23-PS419/petanikita-api#1]
Create an authentication API that will returns user.

Endpoints:
- [x] `POST` /auth/token : Generate token for `User`.
- [x] `POST` /auth/register : Create new `User`.
- [x] `GET` /auth/logout : Revoke `User`'s token.
- [x] `GET` /auth/user : Get current logged in `User` information.

**Comment by dimas-ishaq** [comment]
POST /register : Register New User
POST /login : User Login & Return token
GET /logout : Revoke User's token.
GET /users : GET All User
GET /users/{id} : GET Single User
PUT /users/{id} : Update User By Id
DELETE  /users/{id} : Delete User By Id
POST /products : Create Product
GET /products : Get All Product
GET /products/{id} : Get Single Product
GET /products/search : Search Product By Name
PUT /products/{id} : Update Product By Id
DELETE /products/{id} : Delete Product By Id

https://github.com/dimas-ishaq/petanikita-test-api/tree/petanikita-test-api

**Comment by risangbaskoro** [comment]
@dimas-ishaq route lain bisa dibuka menggunakan issue dan pull request lain, sesuai fitur.
